config/routes.rb
Rails.application.routes.draw do
  resources :pricings
  resources :vendors
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pricing.rb
class Pricing < ApplicationRecord
  belongs_to :vendor, :foreign_key => 'vendor_id'
  belongs_to :product, :foreign_key => 'product_id'
end

/ Pricing Association Table is DONE /

app/models/product.rb
class Product < ApplicationRecord
  has_many :pricings
  has_many :vendors,:through =>:pricings
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  has_many :pricings
  has_many :products, :through=> :pricings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pricings_controller.rb
class PricingsController < ApplicationController
  before_action :set_pricing, only: [:show, :edit, :update, :destroy]

  # GET /pricings
  # GET /pricings.json
  def index
    @pricings = Pricing.all
  end

  # GET /pricings/1
  # GET /pricings/1.json
  def show
  end

  # GET /pricings/new
  def new
    @pricing = Pricing.new
  end

  # GET /pricings/1/edit
  def edit
  end

  # POST /pricings
  # POST /pricings.json
  def create
    @pricing = Pricing.new(pricing_params)

    respond_to do |format|
      if @pricing.save
        format.html { redirect_to @pricing, notice: 'Pricing was successfully created.' }
        format.json { render :show, status: :created, location: @pricing }
      else
        format.html { render :new }
        format.json { render json: @pricing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pricings/1
  # PATCH/PUT /pricings/1.json
  def update
    respond_to do |format|
      if @pricing.update(pricing_params)
        format.html { redirect_to @pricing, notice: 'Pricing was successfully updated.' }
        format.json { render :show, status: :ok, location: @pricing }
      else
        format.html { render :edit }
        format.json { render json: @pricing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pricings/1
  # DELETE /pricings/1.json
  def destroy
    @pricing.destroy
    respond_to do |format|
      format.html { redirect_to pricings_url, notice: 'Pricing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pricing
      @pricing = Pricing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pricing_params
      params.require(:pricing).permit(:price, :quantitydiscount, :vendor_id, :product_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:productname, :productprice)
    end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
    @products = Product.all
    @pricing = Pricing.all
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
    @vendors = Vendor.all
    @products = Product.all
    @pricing = Pricing.all
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:vendorname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pricings_helper.rb
module PricingsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GitInclassactivityPushpull</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pricings/_form.html.erb
<%= form_with(model: pricing, local: true) do |form| %>
  <% if pricing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pricing.errors.count, "error") %> prohibited this pricing from being saved:</h2>

      <ul>
      <% pricing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :vendor_id %>
    <%= form.text_field :vendor_id, vendor.all :id, :name %>

  </div>

  <div class="field">
    <%= form.label :quantitydiscount %>
    <%= form.text_field :quantitydiscount %>
  </div>

  <div class="field">
    <%= form.collection_select :vendor_id, Vendor.all, :id ,:vendorname %>


  </div>

  <div class="field">
    <%= form.collection_select :product_id, Product.all, :id ,:productname %>


  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pricings/edit.html.erb
<h1>Editing Pricing</h1>

<%= render 'form', pricing: @pricing %>

<%= link_to 'Show', @pricing %> |
<%= link_to 'Back', pricings_path %>

app/views/pricings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pricings</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Quantitydiscount</th>
      <th>Vendor</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pricings.each do |pricing| %>
      <tr>
        <td><%= pricing.price %></td>
        <td><%= pricing.quantitydiscount %></td>
        <td><%= pricing.vendor.vendorname %></td>
        <td><%= pricing.product.productname %></td>
        <td><%= link_to 'Show', pricing %></td>
        <td><%= link_to 'Edit', edit_pricing_path(pricing) %></td>
        <td><%= link_to 'Destroy', pricing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pricing', new_pricing_path %>

app/views/pricings/new.html.erb
<h1>New Pricing</h1>

<%= render 'form', pricing: @pricing %>

<%= link_to 'Back', pricings_path %>

app/views/pricings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @pricing.price %>
</p>

<p>
  <strong>Quantitydiscount:</strong>
  <%= @pricing.quantitydiscount %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @pricing.vendor.vendorname %>
</p>

<p>
  <strong>Product:</strong>
  <%= @pricing.product %>
</p>

<%= link_to 'Edit', edit_pricing_path(@pricing) %> |
<%= link_to 'Back', pricings_path %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :productnames %>
    <%= form.text_field :productname %>
  </div>

  <div class="field">
    <%= form.label :productprice %>
    <%= form.text_field :productprice %>
  </div>
  <div class="field">
    <%= form.label :vendor_id %>
    <%= form.collection_select :vendor_id, Vendor.all, :id, :vendorname %>
  </div>

  <div class="field">
    <%= form.collection_select :vendor_id, Vendor.all, :id ,:vendorname %>


  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Vendor</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.productname %></td>
        <td><%= product.productprice %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Productname:</strong>
  <%= @product.productname %>
</p>

<p>
  <strong>Productprice:</strong>
  <%= @product.productprice %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/vendors/_form.html.erb
<%= form_with(model: vendor, local: true) do |form| %>
  <% if vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vendorname %>
    <%= form.text_field :vendorname %>
  </div>

  <div class="field">
    <%= form.label :productname %>
    <%= form.text_field :pricing, product.productname.all %>
  </div>

  <div class="field">
    <%= form.label :pricing %>
    <%= form.text_field :pricing, productname %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form', vendor: @vendor %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vendors</h1>

<table>
  <thead>
    <tr>
      <th>Vendorname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td><%= vendor.vendorname %></td>
        <td><%= vendor.products%></td>


        <td><%= link_to 'Show', vendor %></td>
        <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
        <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendor', new_vendor_path %>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>

<%= render 'form', vendor: @vendor %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vendorname:</strong>
  <%= @vendor.vendorname %>
</p>

<p>

<table>
<thead>
<tr>
  <th>Productname</th>
  <th>Productprice</th>
  <th colspan="3"></th>
</tr>
</thead>

<tbody>
<% @vendors.each do |vendor| %>
  <tr>
    <td><%= vendor.pricings %></td>



  </tr>
<% end %>
</tbody>
</table>
</p>



<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>